server:
  port: 8083
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/products
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
    tomcat:
      test-while-idle: true     # Keep the connection alive if idle for a long time
      validation-query: 'SELECT 1'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true     # Show or not log for each sql query
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect   # Allows to Hibernate to generate SQL optimized for a particular DBMS

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}

axon:
  eventhandling:
    processors:
      product-group:
        mode: subscribing